/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "zrxfrmbvhbllqcszllsm"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpyeGZybWJ2aGJsbHFjc3psbHNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODUzOTcxNzMsImV4cCI6MjEwMDk3MzE3M30.h_BGS5-VzjDrw-BuctDY6RPPZGbgWRz3ckjuLpb0UNY"